Maintenance/simjplify env
out-of-tune/OOT pull request #97
Opened 2023-09-26 21:33 UTC by millii19

simplified env variables, nginx conf files and removed client-authentication

2023-09-27 09:08 UTC, absurd-turtle approved these changes
LGTM!
I had a few comments but nothing too important.
Good job stripping out unnecessary complexity and the auth stuff :)

2023-09-27 09:22 UTC, absurd-turtle requested changes
My local build doesn't seem to run correctly.
I get `An error occurred during a connection to localhost. PR_END_OF_FILE_ERROR` when I try to reach `https://localhost/`.
Is there something I missed?

2023-09-27 09:26 UTC, absurd-turtle commented
> My local build doesn't seem to run correctly. I get `An error occurred during a connection to localhost. PR_END_OF_FILE_ERROR` when I try to reach `https://localhost/`. Is there something I missed?

Connecting with http at `http://localhost/app/` works as intended though.

2023-09-27 10:04 UTC, millii19 commented on api/src/caching/memcached.ts
> +import { MEMCACHED_HOST } from "../helpers/settings.js";
This is one of the limitations of typescript+ES modules, the imports need to be .js

2023-09-27 10:05 UTC, millii19 commented on api/src/helpers/settings.ts
> +export const SPOTIFY_SCOPE = process.env.SPOTIFY_SCOPE
I'm working on an improvement for the environment settings, there I will add the default.

2023-09-27 10:06 UTC, millii19 commented on api/src/helpers/settings.ts
> +export const API_PORT = Number.parseInt(process.env.APOLLO_PORT ?? "3003")
Same, there will be nice error handling in the improvement

2023-09-27 12:05 UTC, millii19 commented
both http://localhost and http://localhost/app work for me, when I run the docker compose locally

2023-09-29 09:21 UTC, absurd-turtle approved these changes

2023-09-30 13:59 UTC, merged